name: "Deploy"

on: 
  push:
    branches: [master]
    

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Setupt node
        uses: actions/setup-node@v2.1.5
        with: 
          node-version: 15.x

      - name: install dependencies
        run: yarn    
      
      - name: build
        run: yarn build
        
      - name: change package version
        run: npm version patch
          
      - name: publish
        run: npm publish
      
      
    
    

    
  


  
